name: 'Action Analyze'
description: 'Dumps information about the steps in a workflow'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  github-token:
    description: 'Token to use for GitHub API'
    required: true
  owner:
    description: 'Owner of the repository'
    required: true
  repo:
    description: 'Repository name'
    required: true
  workflow-id:
    description: 'Workflow ID'
    required: true
  job-name:
    description: 'Job name'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'