name: 'Action Analyze'
description: 'Dumps information about the steps in a workflow'
inputs:
  github-token:
    description: 'Token to use for GitHub API'
    required: true
  repo:
    description: 'Repository name'
    required: true
  workflow-id:
    description: 'Workflow ID'
    required: true
  job-id:
    description: 'Job ID'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'